g = #Graph
g = g.add_edge('s, 't, 10)
g = g.add_edge('s, 'y, 5)
g = g.add_edge('t, 'x, 1)
g = g.add_edge('t, 'y, 2)
g = g.add_edge('x, 'z, 4)
g = g.add_edge('y, 't, 3)
g = g.add_edge('y, 'x, 9)
g = g.add_edge('y, 'z, 2)
g = g.add_edge('z, 's, 7)
g = g.add_edge('z, 'x, 6)
IO.puts "g => #{g}"
IO.puts "g.dijkstra('s) => #{g.dijkstra('s)}"
IO.puts "g.dijkstra('t) => #{g.dijkstra('t)}"
IO.puts "g.dijkstra('x) => #{g.dijkstra('x)}"
IO.puts "g.dijkstra('y) => #{g.dijkstra('y)}"
IO.puts "g.dijkstra('z) => #{g.dijkstra('z)}"
